stages:
    - build

variables:
  HELM_EXPERIMENTAL_OCI: 1

chartbuild:
    stage: build
    image: gitlab.lab5g.local/root/helm-docker
    tags:
      - docker
    script:

        - helm registry login gitlab.lab5g.local:5050 -u root -p v3jwCcWifNDjvJ28uB2r
        - helm chart save ./ gitlab.lab5g.local:5050/root/openstack-ironic-standalone:1.1.16
        - helm chart push gitlab.lab5g.local:5050/root/openstack-ironic-standalone:1.1.16
