apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.httpboot.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "openstackIronicStandalone.httpboot.fullname" . }}
spec:
  replicas: {{ .Values.httpboot.replicas }}
  selector:
    matchLabels:
      app: {{ include "openstackIronicStandalone.name" . }}
      component: "{{ .Values.httpboot.name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "openstackIronicStandalone.name" . }}
        component: "{{ .Values.httpboot.name }}"
        release: {{ .Release.Name }}
      name: {{ include "openstackIronicStandalone.httpboot.fullname" . }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/httpboot-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: cp-pxelinux
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          command:
            - rsync
            - --ignore-missing-args
            - "/usr/share/syslinux/pxelinux.0"
            - "/usr/share/ipxe/ipxe.efi"
            - "/usr/share/ipxe/undionly.kpxe"
            - "/usr/share/syslinux/custom-ipxe.efi"
            - "/usr/share/syslinux/custom-undionly.kpxe"
            - "/tftpboot/"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /tftpboot
              name: ironic
              subPath: tftpboot
      containers:
      - name: {{ include "openstackIronicStandalone.httpboot.fullname" . }}
        image:  "{{ .Values.httpboot.image.name }}:{{ .Values.httpboot.image.version }}"
      {{- with .Values.httpboot.resources }}
        resources:
{{ toYaml . | indent 10 }}
      {{- end }}
        ports:
        - name: ironic-httpboot
          containerPort: {{ .Values.httpboot.portInternal }}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
          readOnly: true
        - mountPath: /var/www
          name: ironic
          subPath: httpboot
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "openstackIronicStandalone.httpboot.fullname" . }}
          defaultMode: 0644
      - name: ironic
        persistentVolumeClaim:
          {{- if .Values.persistentVolumeClaimName }}
          claimName: {{ .Values.persistentVolumeClaimName | quote }}
          {{- else }}
          claimName: {{ ( include "openstackIronicStandalone.tftp.fullname" . ) | quote }}
          {{- end }}
